$ErrorActionPreference = 'Stop'

$baseDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$outPath = Join-Path $baseDir 'LogSpiral_Excel_VBA_inverted.xlsm'
$modulePath = Join-Path $baseDir 'LogSpiralSolver.bas'

$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

try {
    $wb = $excel.Workbooks.Add()

    while ($wb.Worksheets.Count -lt 4) {
        $null = $wb.Worksheets.Add()
    }

    $wsInputs = $wb.Worksheets.Item(1)
    $wsInputs.Name = 'Inputs'
    $wsScan = $wb.Worksheets.Item(2)
    $wsScan.Name = 'Xi Scan'
    $wsGeom = $wb.Worksheets.Item(3)
    $wsGeom.Name = 'Geometry'
    $wsTables = $wb.Worksheets.Item(4)
    $wsTables.Name = 'Paper Tables'

    $wsInputs.Range('A1').Value2 = 'Log-Spiral Passive Pressure VBA Workbook'
    $wsInputs.Range('A2').Resize(11, 1).Value2 = @(
        @('H'),
        @('γ'),
        @('φ (deg)'),
        @('δ (deg)'),
        @('β (deg)'),
        @('ω (deg)'),
        @('q'),
        @('ξ range mode'),
        @('ξ_min'),
        @('ξ_max'),
        @('n_ξ')
    )
    $wsInputs.Range('B2').Value2 = 0.24
    $wsInputs.Range('B3').Value2 = 15.3
    $wsInputs.Range('B4').Value2 = 35.5
    $wsInputs.Range('B5').Value2 = 24
    $wsInputs.Range('B6').Value2 = 0
    $wsInputs.Range('B7').Value2 = 0
    $wsInputs.Range('B8').Value2 = 0
    $wsInputs.Range('B9').Value2 = 'Auto'
    $wsInputs.Range('B10').Value2 = -0.5
    $wsInputs.Range('B11').Value2 = 0.25
    $wsInputs.Range('B12').Value2 = 250

    $wsInputs.Range('D2').Value2 = 'Buttons'
    $button1 = $wsInputs.Buttons().Add(220, 35, 120, 28)
    $button1.Characters().Text = 'Run ξ Scan'
    $button1.OnAction = 'RunXiScan'
    $button2 = $wsInputs.Buttons().Add(220, 70, 120, 28)
    $button2.Characters().Text = 'Build kp Tables'
    $button2.OnAction = 'BuildConclusionTables'
    $button3 = $wsInputs.Buttons().Add(220, 105, 120, 28)
    $button3.Characters().Text = 'Reset Inputs'
    $button3.OnAction = 'ResetInputs'

    $wsGeom.Range('A1').Value2 = 'Geometry plot and summary will be generated by Run ξ Scan.'
    $wsScan.Range('A1').Value2 = 'Run the scan macro from the Inputs sheet.'
    $wsTables.Range('A1').Value2 = 'Run Build kp Tables to generate paper-style tables.'

    $null = $wb.VBProject.VBComponents.Import($modulePath)

    $fileFormat = 52
    $wb.SaveAs($outPath, $fileFormat)
    $wb.Close($true)
}
finally {
    $excel.Quit()
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
}

Write-Output "CREATED=$outPath"
